//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن المنتج.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعتماد.
        /// </summary>
        public static string Accreditation {
            get {
                return ResourceManager.GetString("Accreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدليل النشط.
        /// </summary>
        public static string ActiveDirectory {
            get {
                return ResourceManager.GetString("ActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات الدليل النشط.
        /// </summary>
        public static string ActiveDirectorySettings {
            get {
                return ResourceManager.GetString("ActiveDirectorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة الى.
        /// </summary>
        public static string AddedTo {
            get {
                return ResourceManager.GetString("AddedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مرفقات.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة النظام.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدراء النظام.
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مدير نظام.
        /// </summary>
        public static string AdministratorsCreate {
            get {
                return ResourceManager.GetString("AdministratorsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم حذف البيانات بنجاح.
        /// </summary>
        public static string AlertDataDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AlertDataDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل البيانات بنجاح.
        /// </summary>
        public static string AlertDataModifiedSuccessfully {
            get {
                return ResourceManager.GetString("AlertDataModifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إستعادة البيانات بنجاح.
        /// </summary>
        public static string AlertDataRestoredSuccessfully {
            get {
                return ResourceManager.GetString("AlertDataRestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ البيانات بنجاح.
        /// </summary>
        public static string AlertDataSavedSuccessfully {
            get {
                return ResourceManager.GetString("AlertDataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء عملية الحذف.
        /// </summary>
        public static string AlertErrorDeletingData {
            get {
                return ResourceManager.GetString("AlertErrorDeletingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء عملية التعديل.
        /// </summary>
        public static string AlertErrorModifyingData {
            get {
                return ResourceManager.GetString("AlertErrorModifyingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء عملية الحفظ.
        /// </summary>
        public static string AlertErrorSavingData {
            get {
                return ResourceManager.GetString("AlertErrorSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعتماد المحضر لا يمكن تغيير الحالة.
        /// </summary>
        public static string AlertMeetingMinutesIsClosed {
            get {
                return ResourceManager.GetString("AlertMeetingMinutesIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب دعوة عضو واحد على الاقل في هذا الاجتماع.
        /// </summary>
        public static string AlertMeetingUserAddingError {
            get {
                return ResourceManager.GetString("AlertMeetingUserAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في النظام.
        /// </summary>
        public static string AlertSystemError {
            get {
                return ResourceManager.GetString("AlertSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صباحاً.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التطبيقات.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتمد.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع إلى الرئيسية.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع إلى القائمة الرئيسية.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بايت.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقويم.
        /// </summary>
        public static string Calender {
            get {
                return ResourceManager.GetString("Calender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التاريخ.
        /// </summary>
        public static string CalenderType {
            get {
                return ResourceManager.GetString("CalenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء الأمر.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إرسال المواضيع لنفس اللجنة.
        /// </summary>
        public static string CannotTransferToSameCommittee {
            get {
                return ResourceManager.GetString("CannotTransferToSameCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير الصورة.
        /// </summary>
        public static string ChangePicture {
            get {
                return ResourceManager.GetString("ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد أنك تريد حذف هذا العنصر.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التواصل.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معطل.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القرار مستخدم مسبقا.
        /// </summary>
        public static string DecisionNumberAlreadyExist {
            get {
                return ResourceManager.GetString("DecisionNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف قالب صلاحية.
        /// </summary>
        public static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الصورة.
        /// </summary>
        public static string DeletePicture {
            get {
                return ResourceManager.GetString("DeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف صلاحية.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مستخدم.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخة تجريبية.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النطاق.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدة.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمكين SSL.
        /// </summary>
        public static string EmailEnableSSL {
            get {
                return ResourceManager.GetString("EmailEnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضيف.
        /// </summary>
        public static string EmailHost {
            get {
                return ResourceManager.GetString("EmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنفذ.
        /// </summary>
        public static string EmailPort {
            get {
                return ResourceManager.GetString("EmailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات البريد الإلكتروني.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكنك حذف هذا العنصر لإرتباطه بعمليات تم إدخالها مسبقا .
        /// </summary>
        public static string ErrorDeletingItem {
            get {
                return ResourceManager.GetString("ErrorDeletingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من خارج المؤسسة.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد طلب إعادة كلمة المرور.
        /// </summary>
        public static string ForgotConfirmation {
            get {
                return ResourceManager.GetString("ForgotConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال الرابط ، يرجى التحقق من بريدك الإلكتروني لإعادة تعيين كلمة المرور الخاصة بك..
        /// </summary>
        public static string ForgotConfirmationMessage {
            get {
                return ResourceManager.GetString("ForgotConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل نسيت كلمة المرور؟.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم سابق.
        /// </summary>
        public static string Former {
            get {
                return ResourceManager.GetString("Former", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعتماد الكلي.
        /// </summary>
        public static string FullAccreditation {
            get {
                return ResourceManager.GetString("FullAccreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات العامة.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات العامة.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جيجابايت.
        /// </summary>
        public static string GigaByte {
            get {
                return ResourceManager.GetString("GigaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب صلاحية.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوالب الصلاحيات.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة قالب صلاحية.
        /// </summary>
        public static string GroupsCreate {
            get {
                return ResourceManager.GetString("GroupsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل قالب صلاحية.
        /// </summary>
        public static string GroupsEdit {
            get {
                return ResourceManager.GetString("GroupsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجري.
        /// </summary>
        public static string Hegira {
            get {
                return ResourceManager.GetString("Hegira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساعدة.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنا.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من داخل المؤسسة.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة المرور غير صحيحة.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حاولت أكثر من 5 مرات، حسابك مغلق مؤقتاً، الرجاء المحاولة بعد 15 دقيقة.
        /// </summary>
        public static string IsLockedOut {
            get {
                return ResourceManager.GetString("IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إصدار التقرير.
        /// </summary>
        public static string IssuingReport {
            get {
                return ResourceManager.GetString("IssuingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العنصر موجود مسبقا.
        /// </summary>
        public static string ItemAlreadyExist {
            get {
                return ResourceManager.GetString("ItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيلوبايت.
        /// </summary>
        public static string KiloByte {
            get {
                return ResourceManager.GetString("KiloByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميغابايت.
        /// </summary>
        public static string MegaByte {
            get {
                return ResourceManager.GetString("MegaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العضوية.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميلادي.
        /// </summary>
        public static string Miladi {
            get {
                return ResourceManager.GetString("Miladi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشهر.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من الإجابات.
        /// </summary>
        public static string MoreAnswers {
            get {
                return ResourceManager.GetString("MoreAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من المرفقات.
        /// </summary>
        public static string MoreFiles {
            get {
                return ResourceManager.GetString("MoreFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyCommittees {
            get {
                return ResourceManager.GetString("MyCommittees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع التالي.
        /// </summary>
        public static string NextTopice {
            get {
                return ResourceManager.GetString("NextTopice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد عناصر.
        /// </summary>
        public static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إضافة صلاحيات بعد.
        /// </summary>
        public static string NoRoles {
            get {
                return ResourceManager.GetString("NoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الإعتماد.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التنبيهات.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التوقيع.
        /// </summary>
        public static string NotSignatured {
            get {
                return ResourceManager.GetString("NotSignatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد مستخدمين من.
        /// </summary>
        public static string NoUsersAre {
            get {
                return ResourceManager.GetString("NoUsersAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متصل.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متصل.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور وتأكيد كلمة المرور لم يتطابقا.
        /// </summary>
        public static string PasswordComparison {
            get {
                return ResourceManager.GetString("PasswordComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الإنتظار.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- الرجاء الإختيار --.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساءاً.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الخصوصية.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور.
        /// </summary>
        public static string Presents {
            get {
                return ResourceManager.GetString("Presents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع السابق.
        /// </summary>
        public static string PrevTopice {
            get {
                return ResourceManager.GetString("PrevTopice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الشخصية.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إزالة من .
        /// </summary>
        public static string RemoveFrom {
            get {
                return ResourceManager.GetString("RemoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التقرير.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين كلمة المرور.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد إعادة تعيين كلمة المرور.
        /// </summary>
        public static string ResetConfirmation {
            get {
                return ResourceManager.GetString("ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تعيين كلمة المرور الخاصة بك. يرجى النقر على {0} لتسجيل الدخول..
        /// </summary>
        public static string ResetConfirmationMessage {
            get {
                return ResourceManager.GetString("ResetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستعادة.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صلاحية.
        /// </summary>
        public static string RolesCreate {
            get {
                return ResourceManager.GetString("RolesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل صلاحية.
        /// </summary>
        public static string RolesEdit {
            get {
                return ResourceManager.GetString("RolesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ التغييرات.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ المحضر.
        /// </summary>
        public static string SaveMinutes {
            get {
                return ResourceManager.GetString("SaveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الكل.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال للإعتماد.
        /// </summary>
        public static string SendAccreditation {
            get {
                return ResourceManager.GetString("SendAccreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال للتوقيع.
        /// </summary>
        public static string SendSignature {
            get {
                return ResourceManager.GetString("SendSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحويل.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوقيع.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التوقيع.
        /// </summary>
        public static string Signatured {
            get {
                return ResourceManager.GetString("Signatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الإرسال للتوقيع.
        /// </summary>
        public static string SignatureNotSend {
            get {
                return ResourceManager.GetString("SignatureNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من انك تريد حفظ المحضر؟.
        /// </summary>
        public static string SureSaveMinutes {
            get {
                return ResourceManager.GetString("SureSaveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات النظام.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكام.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختبار.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترحيل المواضيع.
        /// </summary>
        public static string TopicTransfer {
            get {
                return ResourceManager.GetString("TopicTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع محول.
        /// </summary>
        public static string TransferedTopic {
            get {
                return ResourceManager.GetString("TransferedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء التحويل.
        /// </summary>
        public static string TransferRejected {
            get {
                return ResourceManager.GetString("TransferRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترقية النظام.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرفاق.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string Useer {
            get {
                return ResourceManager.GetString("Useer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم مسجل مسبقاً.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المستخدم.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مستخدم.
        /// </summary>
        public static string UsersCreate {
            get {
                return ResourceManager.GetString("UsersCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مستخدم.
        /// </summary>
        public static string UsersEdit {
            get {
                return ResourceManager.GetString("UsersEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب.
        /// </summary>
        public static string ValidationsRequired {
            get {
                return ResourceManager.GetString("ValidationsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الكل.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسبوع.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لديك &lt;strong class=&quot;text-primary&quot;&gt;{0}&lt;/strong&gt; تنبيه..
        /// </summary>
        public static string YouHaveNotifications {
            get {
                return ResourceManager.GetString("YouHaveNotifications", resourceCulture);
            }
        }
    }
}
