//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن المنتج.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم صاحب الحساب.
        /// </summary>
        public static string ACCOUNTNAME {
            get {
                return ResourceManager.GetString("ACCOUNTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب.
        /// </summary>
        public static string ACCOUNTNUMBER {
            get {
                return ResourceManager.GetString("ACCOUNTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعتماد.
        /// </summary>
        public static string Accreditation {
            get {
                return ResourceManager.GetString("Accreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدليل النشط.
        /// </summary>
        public static string ActiveDirectory {
            get {
                return ResourceManager.GetString("ActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات الدليل النشط.
        /// </summary>
        public static string ActiveDirectorySettings {
            get {
                return ResourceManager.GetString("ActiveDirectorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة بنك.
        /// </summary>
        public static string AddChaletBank {
            get {
                return ResourceManager.GetString("AddChaletBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة الى.
        /// </summary>
        public static string AddedTo {
            get {
                return ResourceManager.GetString("AddedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مرفقات.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وحدة جديدة.
        /// </summary>
        public static string AddNewUnit {
            get {
                return ResourceManager.GetString("AddNewUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة حجز.
        /// </summary>
        public static string AddReservation {
            get {
                return ResourceManager.GetString("AddReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة حجز ل .
        /// </summary>
        public static string AddReservationFor {
            get {
                return ResourceManager.GetString("AddReservationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة شاليه مشابه.
        /// </summary>
        public static string AddSimilarChalet {
            get {
                return ResourceManager.GetString("AddSimilarChalet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة النظام.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدراء النظام.
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مدير نظام.
        /// </summary>
        public static string AdministratorsCreate {
            get {
                return ResourceManager.GetString("AdministratorsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم حذف البيانات بنجاح.
        /// </summary>
        public static string AlertDataDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AlertDataDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل البيانات بنجاح.
        /// </summary>
        public static string AlertDataModifiedSuccessfully {
            get {
                return ResourceManager.GetString("AlertDataModifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إستعادة البيانات بنجاح.
        /// </summary>
        public static string AlertDataRestoredSuccessfully {
            get {
                return ResourceManager.GetString("AlertDataRestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ البيانات بنجاح.
        /// </summary>
        public static string AlertDataSavedSuccessfully {
            get {
                return ResourceManager.GetString("AlertDataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء عملية الحذف.
        /// </summary>
        public static string AlertErrorDeletingData {
            get {
                return ResourceManager.GetString("AlertErrorDeletingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء عملية التعديل.
        /// </summary>
        public static string AlertErrorModifyingData {
            get {
                return ResourceManager.GetString("AlertErrorModifyingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ أثناء عملية الحفظ.
        /// </summary>
        public static string AlertErrorSavingData {
            get {
                return ResourceManager.GetString("AlertErrorSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعتماد المحضر لا يمكن تغيير الحالة.
        /// </summary>
        public static string AlertMeetingMinutesIsClosed {
            get {
                return ResourceManager.GetString("AlertMeetingMinutesIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في النظام.
        /// </summary>
        public static string AlertSystemError {
            get {
                return ResourceManager.GetString("AlertSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صباحاً.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التطبيقات.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتمد.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أبريل.
        /// </summary>
        public static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أبريل.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أغسطس.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أغسطس.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع إلى الرئيسية.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع إلى القائمة الرئيسية.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنك.
        /// </summary>
        public static string BANKID {
            get {
                return ResourceManager.GetString("BANKID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنوك.
        /// </summary>
        public static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفضيلات.
        /// </summary>
        public static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستراحة.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصفح ملفاتك.
        /// </summary>
        public static string BrowseFiles {
            get {
                return ResourceManager.GetString("BrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بايت.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقويم.
        /// </summary>
        public static string Calender {
            get {
                return ResourceManager.GetString("Calender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التاريخ.
        /// </summary>
        public static string CalenderType {
            get {
                return ResourceManager.GetString("CalenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء الأمر.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string CancelTrans {
            get {
                return ResourceManager.GetString("CancelTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور المنتجع.
        /// </summary>
        public static string CHALETIMAGES {
            get {
                return ResourceManager.GetString("CHALETIMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المنتجع.
        /// </summary>
        public static string ChaletInfo {
            get {
                return ResourceManager.GetString("ChaletInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المنتجع.
        /// </summary>
        public static string ChaletName {
            get {
                return ResourceManager.GetString("ChaletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجعات.
        /// </summary>
        public static string Chalets {
            get {
                return ResourceManager.GetString("Chalets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات المنتجع.
        /// </summary>
        public static string ChaletSetting {
            get {
                return ResourceManager.GetString("ChaletSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير الصورة.
        /// </summary>
        public static string ChangePicture {
            get {
                return ResourceManager.GetString("ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب المحافظة على نظافة الشاليه..
        /// </summary>
        public static string CLEANCONDITION {
            get {
                return ResourceManager.GetString("CLEANCONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط إضافة الصور.
        /// </summary>
        public static string ConditionOfAddImages {
            get {
                return ResourceManager.GetString("ConditionOfAddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التأكيد.
        /// </summary>
        public static string ConfirmCode {
            get {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد أنك تريد حذف هذا العنصر.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤكد.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بتفعيل حسابك.
        /// </summary>
        public static string ConfirmYourAccount {
            get {
                return ResourceManager.GetString("ConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;icon-envelope2&quot;&gt;&lt;/i&gt; info@canvas.com &lt;span class=&quot;middot&quot;&gt;·&lt;/span&gt; &lt;i class=&quot;icon-headphones&quot;&gt;&lt;/i&gt; +1-11-6541-6369 &lt;span class=&quot;middot&quot;&gt;·&lt;/span&gt; &lt;i class=&quot;icon-skype2&quot;&gt;&lt;/i&gt; CanvasOnSkype
        ///                        &lt;/div&gt;.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التواصل.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة © {0}.
        /// </summary>
        public static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة شاليه جديد.
        /// </summary>
        public static string CreateNewChalet {
            get {
                return ResourceManager.GetString("CreateNewChalet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ من.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ إلى.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر اليوم.
        /// </summary>
        public static string DayPrice {
            get {
                return ResourceManager.GetString("DayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معطل.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ديسمبر.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ديسمبر.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القرار مستخدم مسبقا.
        /// </summary>
        public static string DecisionNumberAlreadyExist {
            get {
                return ResourceManager.GetString("DecisionNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف قالب صلاحية.
        /// </summary>
        public static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الصورة.
        /// </summary>
        public static string DeletePicture {
            get {
                return ResourceManager.GetString("DeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف صلاحية.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مستخدم.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخة تجريبية.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربون المطلوب لتأكيد الحجز.
        /// </summary>
        public static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف بالشاليه.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإتجاه.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النطاق.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسحب وافلت.
        /// </summary>
        public static string DragAndDrop {
            get {
                return ResourceManager.GetString("DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدة.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرق.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمكين SSL.
        /// </summary>
        public static string EmailEnableSSL {
            get {
                return ResourceManager.GetString("EmailEnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضيف.
        /// </summary>
        public static string EmailHost {
            get {
                return ResourceManager.GetString("EmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنفذ.
        /// </summary>
        public static string EmailPort {
            get {
                return ResourceManager.GetString("EmailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات البريد الإلكتروني.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الدخول.
        /// </summary>
        public static string ENTERTIME {
            get {
                return ResourceManager.GetString("ENTERTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل رمز التفعيل.
        /// </summary>
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكنك حذف هذا العنصر لإرتباطه بعمليات تم إدخالها مسبقا .
        /// </summary>
        public static string ErrorDeletingItem {
            get {
                return ResourceManager.GetString("ErrorDeletingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الخروج.
        /// </summary>
        public static string EXITTIME {
            get {
                return ResourceManager.GetString("EXITTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من خارج المؤسسة.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشاليه للعوائل فقط ويمنع تأجير العزاب.
        /// </summary>
        public static string FamilyCondition {
            get {
                return ResourceManager.GetString("FamilyCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فبراير.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فبراير.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الأول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليوم.
        /// </summary>
        public static string ForDay {
            get {
                return ResourceManager.GetString("ForDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد طلب إعادة كلمة المرور.
        /// </summary>
        public static string ForgotConfirmation {
            get {
                return ResourceManager.GetString("ForgotConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال الرابط ، يرجى التحقق من بريدك الإلكتروني لإعادة تعيين كلمة المرور الخاصة بك..
        /// </summary>
        public static string ForgotConfirmationMessage {
            get {
                return ResourceManager.GetString("ForgotConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل نسيت كلمة المرور؟.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم سابق.
        /// </summary>
        public static string Former {
            get {
                return ResourceManager.GetString("Former", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعة.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعة.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعتماد الكلي.
        /// </summary>
        public static string FullAccreditation {
            get {
                return ResourceManager.GetString("FullAccreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات العامة.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات العامة.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جيجابايت.
        /// </summary>
        public static string GigaByte {
            get {
                return ResourceManager.GetString("GigaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب صلاحية.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المجموعة.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوالب الصلاحيات.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة قالب صلاحية.
        /// </summary>
        public static string GroupsCreate {
            get {
                return ResourceManager.GetString("GroupsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل قالب صلاحية.
        /// </summary>
        public static string GroupsEdit {
            get {
                return ResourceManager.GetString("GroupsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد شاليهات مشابهة له في السعر والمواصفات عددها.
        /// </summary>
        public static string HaveSimilarChalets {
            get {
                return ResourceManager.GetString("HaveSimilarChalets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجري.
        /// </summary>
        public static string Hegira {
            get {
                return ResourceManager.GetString("Hegira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساعدة.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنا.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الأيبان.
        /// </summary>
        public static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يقل عدد الصور عن 4..
        /// </summary>
        public static string ImageCountDontLessThan4 {
            get {
                return ResourceManager.GetString("ImageCountDontLessThan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصور.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الواجهة.
        /// </summary>
        public static string InterfaceImage {
            get {
                return ResourceManager.GetString("InterfaceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من داخل المؤسسة.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة المرور غير صحيحة.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حاولت أكثر من 5 مرات، حسابك مغلق مؤقتاً، الرجاء المحاولة بعد 15 دقيقة.
        /// </summary>
        public static string IsLockedOut {
            get {
                return ResourceManager.GetString("IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إصدار التقرير.
        /// </summary>
        public static string IssuingReport {
            get {
                return ResourceManager.GetString("IssuingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العنصر موجود مسبقا.
        /// </summary>
        public static string ItemAlreadyExist {
            get {
                return ResourceManager.GetString("ItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يناير.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يناير.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوليو.
        /// </summary>
        public static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوليو.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يونيو.
        /// </summary>
        public static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يونيو.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيلوبايت.
        /// </summary>
        public static string KiloByte {
            get {
                return ResourceManager.GetString("KiloByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الأخير.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع على الخريطة.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول/تسجيل.
        /// </summary>
        public static string LoginRegister {
            get {
                return ResourceManager.GetString("LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مارس.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مارس.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مايو.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميغابايت.
        /// </summary>
        public static string MegaByte {
            get {
                return ResourceManager.GetString("MegaByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العضوية.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميلادي.
        /// </summary>
        public static string Miladi {
            get {
                return ResourceManager.GetString("Miladi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأثنين.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأثنين.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتعهد بأني المسؤول من صحة التحويل البنكي (الإيصال) عند كل حجز من الموقع.
        /// </summary>
        public static string MONEYTRANSFERCONDITION {
            get {
                return ResourceManager.GetString("MONEYTRANSFERCONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشهر.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من الإجابات.
        /// </summary>
        public static string MoreAnswers {
            get {
                return ResourceManager.GetString("MoreAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من المرفقات.
        /// </summary>
        public static string MoreFiles {
            get {
                return ResourceManager.GetString("MoreFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إضافة صورة للمجلس الخارجي.
        /// </summary>
        public static string MostAddExternalCouncil {
            get {
                return ResourceManager.GetString("MostAddExternalCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إضافة صورة للفناء الخارجي.
        /// </summary>
        public static string MostAddOutdoorPatio {
            get {
                return ResourceManager.GetString("MostAddOutdoorPatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إضافة صور لغرف النوم.
        /// </summary>
        public static string MostAddSleepRooms {
            get {
                return ResourceManager.GetString("MostAddSleepRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إضافة صور للمسبح.
        /// </summary>
        public static string MostAddSwimmingPoolImage {
            get {
                return ResourceManager.GetString("MostAddSwimmingPoolImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يدفع عند الوصول ويسترجع عند المغادرة في حال تم التأكد من سلامة ممتلكات الشاليه.
        /// </summary>
        public static string MostPaid {
            get {
                return ResourceManager.GetString("MostPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابي.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتجعاتي.
        /// </summary>
        public static string MyChalets {
            get {
                return ResourceManager.GetString("MyChalets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MyCommittees {
            get {
                return ResourceManager.GetString("MyCommittees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتيري.
        /// </summary>
        public static string MyInvoices {
            get {
                return ResourceManager.GetString("MyInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحي.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاليه جديد.
        /// </summary>
        public static string NewChalet {
            get {
                return ResourceManager.GetString("NewChalet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع التالي.
        /// </summary>
        public static string NextTopice {
            get {
                return ResourceManager.GetString("NextTopice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد عناصر.
        /// </summary>
        public static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إضافة صلاحيات بعد.
        /// </summary>
        public static string NoRoles {
            get {
                return ResourceManager.GetString("NoRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شمال.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشمال الشرقي.
        /// </summary>
        public static string Northeast {
            get {
                return ResourceManager.GetString("Northeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشمال الغربي.
        /// </summary>
        public static string NorthWest {
            get {
                return ResourceManager.GetString("NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الإعتماد.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متوفر.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملحوظة.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التنبيهات.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم التوقيع.
        /// </summary>
        public static string NotSignatured {
            get {
                return ResourceManager.GetString("NotSignatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد وحدات.
        /// </summary>
        public static string NoUnits {
            get {
                return ResourceManager.GetString("NoUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد مستخدمين من.
        /// </summary>
        public static string NoUsersAre {
            get {
                return ResourceManager.GetString("NoUsersAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوفمبر.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوفمبر.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أكتوبر.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أكتوبر.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسعار خاصة لفترة معينة.
        /// </summary>
        public static string OfferLabel {
            get {
                return ResourceManager.GetString("OfferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متصل.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجوزات سابقة.
        /// </summary>
        public static string OldReservations {
            get {
                return ResourceManager.GetString("OldReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متصل.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرط آخر.
        /// </summary>
        public static string OTHERCONDITION {
            get {
                return ResourceManager.GetString("OTHERCONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الباراميتير.
        /// </summary>
        public static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور وتأكيد كلمة المرور لم يتطابقا.
        /// </summary>
        public static string PasswordComparison {
            get {
                return ResourceManager.GetString("PasswordComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الدفع.
        /// </summary>
        public static string PaymentInfo {
            get {
                return ResourceManager.GetString("PaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الإنتظار.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- الرجاء الإختيار --.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساءاً.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الخصوصية.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور.
        /// </summary>
        public static string Presents {
            get {
                return ResourceManager.GetString("Presents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع السابق.
        /// </summary>
        public static string PrevTopice {
            get {
                return ResourceManager.GetString("PrevTopice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر بحسب اليوم.
        /// </summary>
        public static string PricePerDay {
            get {
                return ResourceManager.GetString("PricePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الخصوصية.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الشخصية.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتعهد بأني مسؤول عن تحديث الأسعار في حال تغيرها، وأي حجز يتم عن طريق التطبيق او الموقع ولم احدث السعر أتحمل .مسؤولية ذلك وإدارة موقع أو تطبيق سائح غير مسؤولة عن ذلك.
        /// </summary>
        public static string PromiseChangePrices {
            get {
                return ResourceManager.GetString("PromiseChangePrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العقار.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إزالة من .
        /// </summary>
        public static string RemoveFrom {
            get {
                return ResourceManager.GetString("RemoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التقرير.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوم.
        /// </summary>
        public static string ReservationDay {
            get {
                return ResourceManager.GetString("ReservationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أيام.
        /// </summary>
        public static string ReservationDays {
            get {
                return ResourceManager.GetString("ReservationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الحجز.
        /// </summary>
        public static string ReservationDetails {
            get {
                return ResourceManager.GetString("ReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إقامة لمدة.
        /// </summary>
        public static string ReservationFor {
            get {
                return ResourceManager.GetString("ReservationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم مدير الحجوزات.
        /// </summary>
        public static string RESERVATIONMANAGER {
            get {
                return ResourceManager.GetString("RESERVATIONMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجز رقم.
        /// </summary>
        public static string ReservationNumber {
            get {
                return ResourceManager.GetString("ReservationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هاتف مدير الحجوزات.
        /// </summary>
        public static string RESERVATIONPHONENUMBER {
            get {
                return ResourceManager.GetString("RESERVATIONPHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحجوزات.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقويم الحجوزات.
        /// </summary>
        public static string ReservationsCalender {
            get {
                return ResourceManager.GetString("ReservationsCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلزمات صاحب الحجز.
        /// </summary>
        public static string ReservationUserInfo {
            get {
                return ResourceManager.GetString("ReservationUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين كلمة المرور.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد إعادة تعيين كلمة المرور.
        /// </summary>
        public static string ResetConfirmation {
            get {
                return ResourceManager.GetString("ResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تعيين كلمة المرور الخاصة بك. يرجى النقر على {0} لتسجيل الدخول..
        /// </summary>
        public static string ResetConfirmationMessage {
            get {
                return ResourceManager.GetString("ResetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستعادة.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صلاحية.
        /// </summary>
        public static string RolesCreate {
            get {
                return ResourceManager.GetString("RolesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل صلاحية.
        /// </summary>
        public static string RolesEdit {
            get {
                return ResourceManager.GetString("RolesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبت.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبت.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ التغييرات.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ المحضر.
        /// </summary>
        public static string SaveMinutes {
            get {
                return ResourceManager.GetString("SaveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الكل.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر ملف.
        /// </summary>
        public static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال للإعتماد.
        /// </summary>
        public static string SendAccreditation {
            get {
                return ResourceManager.GetString("SendAccreditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرسل مرة اخرى.
        /// </summary>
        public static string SendAgin {
            get {
                return ResourceManager.GetString("SendAgin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال للتوقيع.
        /// </summary>
        public static string SendSignature {
            get {
                return ResourceManager.GetString("SendSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحويل.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبتمبر.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبتمبر.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوقيع.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التوقيع.
        /// </summary>
        public static string Signatured {
            get {
                return ResourceManager.GetString("Signatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الإرسال للتوقيع.
        /// </summary>
        public static string SignatureNotSend {
            get {
                return ResourceManager.GetString("SignatureNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنوب.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنوب الشرقي.
        /// </summary>
        public static string Southeast {
            get {
                return ResourceManager.GetString("Southeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنوب غرب.
        /// </summary>
        public static string Southwest {
            get {
                return ResourceManager.GetString("Southwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحد.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحد.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من انك تريد حفظ المحضر؟.
        /// </summary>
        public static string SureSaveMinutes {
            get {
                return ResourceManager.GetString("SureSaveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالة نظام.
        /// </summary>
        public static string SystemAlert {
            get {
                return ResourceManager.GetString("SystemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات النظام.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكام.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكام.
        /// </summary>
        public static string TermsofUse {
            get {
                return ResourceManager.GetString("TermsofUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختبار.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد تأمين بمبلغ.
        /// </summary>
        public static string thereInsurance {
            get {
                return ResourceManager.GetString("thereInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخميس.
        /// </summary>
        public static string Thurs {
            get {
                return ResourceManager.GetString("Thurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخميس.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترحيل المواضيع.
        /// </summary>
        public static string TopicTransfer {
            get {
                return ResourceManager.GetString("TopicTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع محول.
        /// </summary>
        public static string TransferedTopic {
            get {
                return ResourceManager.GetString("TransferedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء التحويل.
        /// </summary>
        public static string TransferRejected {
            get {
                return ResourceManager.GetString("TransferRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثلاثاء.
        /// </summary>
        public static string Tues {
            get {
                return ResourceManager.GetString("Tues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثلاثاء.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الشاليه.
        /// </summary>
        public static string UnitCode {
            get {
                return ResourceManager.GetString("UnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الشاليهات.
        /// </summary>
        public static string UnitCount {
            get {
                return ResourceManager.GetString("UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الشاليه.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشاليهات.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحة الشاليه.
        /// </summary>
        public static string UnitSpace {
            get {
                return ResourceManager.GetString("UnitSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجوزات قادمة.
        /// </summary>
        public static string UpcomingReservations {
            get {
                return ResourceManager.GetString("UpcomingReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترقية النظام.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرفاق.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string Useer {
            get {
                return ResourceManager.GetString("Useer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم مسجل مسبقاً.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المستخدم.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مستخدم.
        /// </summary>
        public static string UsersCreate {
            get {
                return ResourceManager.GetString("UsersCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل مستخدم.
        /// </summary>
        public static string UsersEdit {
            get {
                return ResourceManager.GetString("UsersEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validations.
        /// </summary>
        public static string Validations {
            get {
                return ResourceManager.GetString("Validations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب.
        /// </summary>
        public static string ValidationsRequired {
            get {
                return ResourceManager.GetString("ValidationsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الكل.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الظهور.
        /// </summary>
        public static string ViewStatus {
            get {
                return ResourceManager.GetString("ViewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير معروض.
        /// </summary>
        public static string ViewStatusHidden {
            get {
                return ResourceManager.GetString("ViewStatusHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معروض.
        /// </summary>
        public static string ViewStatusShown {
            get {
                return ResourceManager.GetString("ViewStatusShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأربعاء.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأربعاء.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسبوع.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غرب.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الواتساب.
        /// </summary>
        public static string WhatsAppNumber {
            get {
                return ResourceManager.GetString("WhatsAppNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هاتف غير صحيح.
        /// </summary>
        public static string WrongPhoneNumber {
            get {
                return ResourceManager.GetString("WrongPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك حساب لدينا سوف يتم إرسال بريد إلكتروني لإنشاء حساب جديد.
        /// </summary>
        public static string YouDontHaveAccount {
            get {
                return ResourceManager.GetString("YouDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك شاليهات .
        /// </summary>
        public static string YouDontHaveChalet {
            get {
                return ResourceManager.GetString("YouDontHaveChalet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لديك &lt;strong class=&quot;text-primary&quot;&gt;{0}&lt;/strong&gt; تنبيه..
        /// </summary>
        public static string YouHaveNotifications {
            get {
                return ResourceManager.GetString("YouHaveNotifications", resourceCulture);
            }
        }
    }
}
